version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  example-job:
    machine:
      image: ubuntu-2004:2022.04.1

    steps:
      - checkout

      - run:
          name: Start LocalStack
          command: |
            pip3 install localstack awscli-local[ver1]
            docker pull localstack/localstack
            localstack start -d                     

            echo "Waiting for LocalStack startup..."  
            localstack wait -t 30                     
            echo "Startup complete"

      - run:
          name: Run AWS CLI commands against LocalStack
          command: |
            awslocal s3 mb s3://test-bucket
            awslocal sqs create-queue --queue-name test-queue
            awslocal sns create-topic --name test-topic

workflows:
  build:
    jobs:
      - example-job
