name: integration-test
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
jobs:
  localstack:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack-pro:latest
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          ACTIVATE_PRO: 1
          DEBUG: 1
        ports:
          - 4566:4566
          - 4510-4559:4510-4559
    env:
      LOCALSTACK_HOST: localhost.localstack.cloud
    steps:
      # Get code
      - uses: actions/checkout@v3
      # Start LocalStack
      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1] aws-sam-cli-local   # install LocalStack cli, awslocal, and SAM cli
          echo "Startup complete"
      - name: Create S3 Bucket
        run: awslocal s3 mb s3://devtestprodaws
      # Setup Bun
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      # Build Lambda Layer
      - name: Build Lambda Layer
        working-directory: ./Lambda/Layer/nodejs
        run: |
          bun i
          bun run compile
      # Build and deploy SAM template
      - name: Deploy SAM Template
        working-directory: ./Cloudformation
        run: |
          samlocal build --template-file template.yaml
          samlocal deploy --config-file samconfig.toml --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --debug
      - name: Get function url
        run: |
          echo FUNCTION_URL=$(awslocal lambda list-function-url-configs --function-name devtestprodaws-main | grep -o '"FunctionUrl": "[^"]*' | awk -F'"' '{print $4}') >> $GITHUB_ENV
      # Run integration tests
      - name: Run integration tests
        working-directory: ./Lambda/__test__/integration
        run: |
          bun test lambdaInvoke.test.ts
          bun test integration.test.ts
