name: test
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - run: bun i
            - name: Run tests
              working-directory: ./Lambda/__test__
              env:
                  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
              run: bun test
