name: unit-test
on:
  push:
    branches: ["dev", "main"]
jobs:
  unit-test-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Get code
      - uses: actions/checkout@v4
      # Get AWS credentials
      - name: Configure AWS Credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: us-east-1
      # Setup Bun
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      # Run tests
      - name: Run tests
        working-directory: ./Lambda/__test__/unit
        run: bun test
